### PR TITLE
Avoid to use RC2-128 cipher algorithm because starting from openssl3 has been moved in legacy provider

### LINKED ISSUE #123: Good certificates/private key will be declared as invalid
The integration test should have pick this up, I believe the latest changes from #119 broke the plugin. There seems to be a problem with the handling of private key and the converter, it is used to convert from PKC7 to PKCS8.

```
Aug 25, 2016 9:40:00 AM io.netty.channel.ChannelInitializer exceptionCaught
WARNING: Failed to initialize a channel. Closing: [id: 0x3759a880, L:/127.0.0.1:5044 - R:/127.0.0.1:63831]
java.lang.IllegalArgumentException: Input stream not contain valid certificates.
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:272)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:99)
	at org.logstash.netty.SslSimpleBuilder.build(SslSimpleBuilder.java:107)
	at org.logstash.beats.Server$BeatsInitializer.initChannel(Server.java:132)
	at org.logstash.beats.Server$BeatsInitializer.initChannel(Server.java:99)
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)

### LINKED ISSUE #483: Avoid to use deprecated ciphers in integration tests
**Build scan**:

**Repro line**:
```sh
bundle install
bundle exec rake test:integration:setup
bundle exec rspec spec --tag integration --format=documentation -e "Filebeat TLS Server verification self signed certificate with a passphrase successfully send the events"
```

**Reproduces locally?**:
Yes, on MacOS 
```
Darwin andreas-MBP-2.station 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6020 arm64
```

**Applicable branches**:

**Failure history**:

**Failure excerpt**:
```
Error encrypting key
80A0BFFB01000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-CBC : 50), Properties ()
80A0BFFB01000000:error:11800067:PKCS12 routines:PKCS12_item_i2d_encrypt_ex:encrypt error:crypto/pkcs12/p12_decr.c:193:
80A0BFFB01000000:error:11800067:PKCS12 routines:PKCS8_set0_pbe_ex:encrypt error:crypto/pkcs12/p12_p8e.c:80:
          successfully send the events (FAILED - 1)
```

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

[rn:skip]

## What does this PR do?

Avoid to use a cipher available in open ssl provider-legacy.
Starting from version 3 of OpenSSL `RC2` family of cipher was moved in another package, which is marked for deprecation: 
https://www.openssl.org/docs/man3.0/man7/EVP_CIPHER-RC2.html

This PR updates the cipher used in some openssl interaction inside integration tests.

## Why is it important/What is the impact to the user?

The developer that runs integration tests outside Docker, directly on his host with commands:
```sh
bundle install
bundle exec rake test:integration:setup
bundle exec rspec spec --tag integration --format=documentation -e "Filebeat TLS Server verification self signed certificate with a passphrase successfully send the events"
```
would suffer of a failure due to openssl command invocation.
This can also be verified on a command shell on the host with:
```sh
$> openssl req -x509  -batch -newkey rsa:2048 -keyout certificate.key -out certificate.crt -passout pass:foobar -subj "/C=EU/O=Logstash/CN=localhost"
$> openssl pkcs8 -topk8 -in certificate.key -out certificate.key.pkcs8 -v1 PBE-SHA1-RC2-128 -passin pass:foobar -passout pass:foobar
```

switching algorithm
```sh
$>openssl pkcs8 -topk8 -in certificate.key -out certificate.key.pkcs8 -v1 PBE-SHA1-3DES -passin pass:foobar -passout pass:foobar
```
it successed.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

On a host with installed openssl3 without `rc-` class of ciphers, runs the integration tests:
```sh
bundle install
bundle exec rake test:integration:setup
bundle exec rspec spec --tag integration --format=documentation
```

To verify the list of installed ciphers:
```sh
openssl -h
```
Check in the section `Ciphers commands` there isn't any `rc2-128`

## Related issues

- Closes #483 

## Logs

```
      self signed certificate
        with a passphrase
...+.+...+...........+....+.....+...+....+.....+......+.......+........+....+......+..+.+...........+....+++++++++++++++++++++++++++++++++++++++*....+....+.....+...+.......+....................+.........+.......+...+...........+.+..+++++++++++++++++++++++++++++++++++++++*........+.....+.+.....+.......+..+....+......+.........+..+............+.+.....+.+...............+........+...+....+...+..+...+................+..+............+.+..+.............+.....+.......+..............................+..+............+...+...+....+.....+.+............+...+.....+............+................+......+...+..........................+....+...........+.+...+..+.........+......+.+..+...+....+...+........+.......+........+...+.........+.............+........+.+...........+.......+...+.....+.............+......+...+......+..+.......+...+........+.........+......+.+.....+....+..+.......+..+...+...+....+...+.................+....+..+..................+.......+........+......+.+..+................+..+.......+...+..+............+.........+....+...+..+...+.............+......+......+........+.+.....+.........+......+...+.......+......+............+...+..............+....+......+.....+.........+.+...........+..........+........+.+......+..+.......+.....+..........+..................+..+.....................+....+..............+.+...+...........+.........+...+.......+........+.......+..+.+...+............+..+.......+........+......+.........+.......+......+...+.....+.+.....+...+.+.........+........+....+...+.....................+..+....+...+......+.........+......+..+.......+......+.....+.......+..+.+...........+.+..+...+...+.+......+.................+.......+...+..+...+...+...+....+......+.....+.+......+..+...........................+.+.....+.........+......+.......+......+.........++++++
....+.+..+++++++++++++++++++++++++++++++++++++++*.....+.......+..............+.+..+......+.+....................+...+.+..+.......+..+++++++++++++++++++++++++++++++++++++++*...+............+.+.....++++++
-----
Error encrypting key
80A0BFFB01000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-CBC : 50), Properties ()
80A0BFFB01000000:error:11800067:PKCS12 routines:PKCS12_item_i2d_encrypt_ex:encrypt error:crypto/pkcs12/p12_decr.c:193:
80A0BFFB01000000:error:11800067:PKCS12 routines:PKCS8_set0_pbe_ex:encrypt error:crypto/pkcs12/p12_p8e.c:80:
          successfully send the events (FAILED - 1)

Failures:

  1) Filebeat TLS Server verification self signed certificate with a passphrase successfully send the events
     Failure/Error: fail "failed to run openssl command: #{$?} \n#{cmd}"

     RuntimeError:
       failed to run openssl command: pid 5691 exit 1
       openssl pkcs8 -topk8 -in /var/folders/f2/6ln9srr13hsdp3kwfz68w3940000gn/T/studtmp-c5b333338b8d46f47faf4f09e53d863dd1d42f169fd61aa5e2eee3ad9390/certificate.key -out /var/folders/f2/6ln9srr13hsdp3kwfz68w3940000gn/T/studtmp-c5b333338b8d46f47faf4f09e53d863dd1d42f169fd61aa5e2eee3ad9390/certificate.key.pkcs8 -v1 PBE-SHA1-RC2-128 -passin pass:foobar -passout pass:foobar
     Shared Example Group: "send events" called from ./spec/integration/filebeat_spec.rb:239
     # ./spec/integration/filebeat_spec.rb:229:in `block in <main>'

Finished in 0.14319 seconds (files took 1.8 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/integration/filebeat_spec.rb:207 # Filebeat TLS Server verification self signed certificate with a passphrase successfully send the events

Randomized with seed 28326
```

### CODE REVIEW

**Review by jsvd — APPROVED** [review]
LGTM

File: spec/integration/filebeat_spec.rb [hunk 1]
```diff
@@ -222,7 +222,7 @@
 
             # NOTE: CentOS 7 base image (LS < 7.17) uses OpenSSL 1.0 while later is using Ubuntu 20.04 with OpenSSL 1.1.1
             # the default algorithm for `openssl pkcs8 -topk8` changed to -v2 which Java does not support (see GH-443)
```
Comment (roaksoax) [inline spec/integration/filebeat_spec.rb:224]: Should you also update the comment to properly reference the new related issue?

**Review by roaksoax — APPROVED** [review]
